/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CsrRouteImport } from './routes/csr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ProgrammesYogaRouteImport } from './routes/programmes.yoga'
import { Route as ProgrammesWorkplaceRouteImport } from './routes/programmes.workplace'
import { Route as ProgrammesTrainTheTrainerRouteImport } from './routes/programmes.train-the-trainer'
import { Route as ProgrammesSchoolsRouteImport } from './routes/programmes.schools'
import { Route as ProgrammesImpactPartnerRouteImport } from './routes/programmes.impact-partner'
import { Route as ProgrammesCsrRouteImport } from './routes/programmes.csr'
import { Route as EventsSchoolsRouteImport } from './routes/events.schools'
import { Route as EventsNmmcRouteImport } from './routes/events.nmmc'
import { Route as EventsMijwanRouteImport } from './routes/events.mijwan'
import { Route as EventsCsrRouteImport } from './routes/events.csr'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CsrRoute = CsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammesRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const ProgrammesYogaRoute = ProgrammesYogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesWorkplaceRoute = ProgrammesWorkplaceRouteImport.update({
  id: '/workplace',
  path: '/workplace',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesTrainTheTrainerRoute =
  ProgrammesTrainTheTrainerRouteImport.update({
    id: '/train-the-trainer',
    path: '/train-the-trainer',
    getParentRoute: () => ProgrammesRoute,
  } as any)
const ProgrammesSchoolsRoute = ProgrammesSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesImpactPartnerRoute = ProgrammesImpactPartnerRouteImport.update({
  id: '/impact-partner',
  path: '/impact-partner',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ProgrammesCsrRoute = ProgrammesCsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => ProgrammesRoute,
} as any)
const EventsSchoolsRoute = EventsSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => EventsRoute,
} as any)
const EventsNmmcRoute = EventsNmmcRouteImport.update({
  id: '/nmmc',
  path: '/nmmc',
  getParentRoute: () => EventsRoute,
} as any)
const EventsMijwanRoute = EventsMijwanRouteImport.update({
  id: '/mijwan',
  path: '/mijwan',
  getParentRoute: () => EventsRoute,
} as any)
const EventsCsrRoute = EventsCsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => EventsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-us': typeof WhyUsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/events/csr': typeof EventsCsrRoute
  '/events/mijwan': typeof EventsMijwanRoute
  '/events/nmmc': typeof EventsNmmcRoute
  '/events/schools': typeof EventsSchoolsRoute
  '/programmes/csr': typeof ProgrammesCsrRoute
  '/programmes/impact-partner': typeof ProgrammesImpactPartnerRoute
  '/programmes/schools': typeof ProgrammesSchoolsRoute
  '/programmes/train-the-trainer': typeof ProgrammesTrainTheTrainerRoute
  '/programmes/workplace': typeof ProgrammesWorkplaceRoute
  '/programmes/yoga': typeof ProgrammesYogaRoute
  '/events/': typeof EventsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-us': typeof WhyUsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/events/csr': typeof EventsCsrRoute
  '/events/mijwan': typeof EventsMijwanRoute
  '/events/nmmc': typeof EventsNmmcRoute
  '/events/schools': typeof EventsSchoolsRoute
  '/programmes/csr': typeof ProgrammesCsrRoute
  '/programmes/impact-partner': typeof ProgrammesImpactPartnerRoute
  '/programmes/schools': typeof ProgrammesSchoolsRoute
  '/programmes/train-the-trainer': typeof ProgrammesTrainTheTrainerRoute
  '/programmes/workplace': typeof ProgrammesWorkplaceRoute
  '/programmes/yoga': typeof ProgrammesYogaRoute
  '/events': typeof EventsIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/csr': typeof CsrRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/terms': typeof TermsRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/why-us': typeof WhyUsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/events/csr': typeof EventsCsrRoute
  '/events/mijwan': typeof EventsMijwanRoute
  '/events/nmmc': typeof EventsNmmcRoute
  '/events/schools': typeof EventsSchoolsRoute
  '/programmes/csr': typeof ProgrammesCsrRoute
  '/programmes/impact-partner': typeof ProgrammesImpactPartnerRoute
  '/programmes/schools': typeof ProgrammesSchoolsRoute
  '/programmes/train-the-trainer': typeof ProgrammesTrainTheTrainerRoute
  '/programmes/workplace': typeof ProgrammesWorkplaceRoute
  '/programmes/yoga': typeof ProgrammesYogaRoute
  '/events/': typeof EventsIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/csr'
    | '/donate'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/get-involved'
    | '/impact'
    | '/news'
    | '/privacy'
    | '/programmes'
    | '/resources'
    | '/terms'
    | '/what-we-do'
    | '/why-us'
    | '/admin/dashboard'
    | '/admin/login'
    | '/events/csr'
    | '/events/mijwan'
    | '/events/nmmc'
    | '/events/schools'
    | '/programmes/csr'
    | '/programmes/impact-partner'
    | '/programmes/schools'
    | '/programmes/train-the-trainer'
    | '/programmes/workplace'
    | '/programmes/yoga'
    | '/events/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/csr'
    | '/donate'
    | '/faq'
    | '/gallery'
    | '/get-involved'
    | '/impact'
    | '/news'
    | '/privacy'
    | '/resources'
    | '/terms'
    | '/what-we-do'
    | '/why-us'
    | '/admin/dashboard'
    | '/admin/login'
    | '/events/csr'
    | '/events/mijwan'
    | '/events/nmmc'
    | '/events/schools'
    | '/programmes/csr'
    | '/programmes/impact-partner'
    | '/programmes/schools'
    | '/programmes/train-the-trainer'
    | '/programmes/workplace'
    | '/programmes/yoga'
    | '/events'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/csr'
    | '/donate'
    | '/events'
    | '/faq'
    | '/gallery'
    | '/get-involved'
    | '/impact'
    | '/news'
    | '/privacy'
    | '/programmes'
    | '/resources'
    | '/terms'
    | '/what-we-do'
    | '/why-us'
    | '/admin/dashboard'
    | '/admin/login'
    | '/events/csr'
    | '/events/mijwan'
    | '/events/nmmc'
    | '/events/schools'
    | '/programmes/csr'
    | '/programmes/impact-partner'
    | '/programmes/schools'
    | '/programmes/train-the-trainer'
    | '/programmes/workplace'
    | '/programmes/yoga'
    | '/events/'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CsrRoute: typeof CsrRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRouteWithChildren
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ImpactRoute: typeof ImpactRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  TermsRoute: typeof TermsRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  WhyUsRoute: typeof WhyUsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csr': {
      id: '/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof CsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/programmes/yoga': {
      id: '/programmes/yoga'
      path: '/yoga'
      fullPath: '/programmes/yoga'
      preLoaderRoute: typeof ProgrammesYogaRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/workplace': {
      id: '/programmes/workplace'
      path: '/workplace'
      fullPath: '/programmes/workplace'
      preLoaderRoute: typeof ProgrammesWorkplaceRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/train-the-trainer': {
      id: '/programmes/train-the-trainer'
      path: '/train-the-trainer'
      fullPath: '/programmes/train-the-trainer'
      preLoaderRoute: typeof ProgrammesTrainTheTrainerRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/schools': {
      id: '/programmes/schools'
      path: '/schools'
      fullPath: '/programmes/schools'
      preLoaderRoute: typeof ProgrammesSchoolsRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/impact-partner': {
      id: '/programmes/impact-partner'
      path: '/impact-partner'
      fullPath: '/programmes/impact-partner'
      preLoaderRoute: typeof ProgrammesImpactPartnerRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/programmes/csr': {
      id: '/programmes/csr'
      path: '/csr'
      fullPath: '/programmes/csr'
      preLoaderRoute: typeof ProgrammesCsrRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/events/schools': {
      id: '/events/schools'
      path: '/schools'
      fullPath: '/events/schools'
      preLoaderRoute: typeof EventsSchoolsRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/nmmc': {
      id: '/events/nmmc'
      path: '/nmmc'
      fullPath: '/events/nmmc'
      preLoaderRoute: typeof EventsNmmcRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/mijwan': {
      id: '/events/mijwan'
      path: '/mijwan'
      fullPath: '/events/mijwan'
      preLoaderRoute: typeof EventsMijwanRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/csr': {
      id: '/events/csr'
      path: '/csr'
      fullPath: '/events/csr'
      preLoaderRoute: typeof EventsCsrRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsCsrRoute: typeof EventsCsrRoute
  EventsMijwanRoute: typeof EventsMijwanRoute
  EventsNmmcRoute: typeof EventsNmmcRoute
  EventsSchoolsRoute: typeof EventsSchoolsRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsCsrRoute: EventsCsrRoute,
  EventsMijwanRoute: EventsMijwanRoute,
  EventsNmmcRoute: EventsNmmcRoute,
  EventsSchoolsRoute: EventsSchoolsRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ProgrammesRouteChildren {
  ProgrammesCsrRoute: typeof ProgrammesCsrRoute
  ProgrammesImpactPartnerRoute: typeof ProgrammesImpactPartnerRoute
  ProgrammesSchoolsRoute: typeof ProgrammesSchoolsRoute
  ProgrammesTrainTheTrainerRoute: typeof ProgrammesTrainTheTrainerRoute
  ProgrammesWorkplaceRoute: typeof ProgrammesWorkplaceRoute
  ProgrammesYogaRoute: typeof ProgrammesYogaRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesCsrRoute: ProgrammesCsrRoute,
  ProgrammesImpactPartnerRoute: ProgrammesImpactPartnerRoute,
  ProgrammesSchoolsRoute: ProgrammesSchoolsRoute,
  ProgrammesTrainTheTrainerRoute: ProgrammesTrainTheTrainerRoute,
  ProgrammesWorkplaceRoute: ProgrammesWorkplaceRoute,
  ProgrammesYogaRoute: ProgrammesYogaRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CsrRoute: CsrRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRouteWithChildren,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ImpactRoute: ImpactRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  TermsRoute: TermsRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  WhyUsRoute: WhyUsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
